- cypress/integration/registration_spec.js
- src/App.js
- src/Register.js
- src/form.css
- src/index.css
Small fix of adjusting homepage route and removed cancel button from registration form.
> fix: adjusted homepage route and registration form

- src/App.js
- src/Mentor.js
> fix: linting errors

- src/Register.js
Register form now sends POST request to the API and creates a new user on database.
> feat: can send registration details to api

- README.md
- Removed 'API' from the title. 
- Added info for running the tests.
> docs: update README with correct title and test info

- src/components/Register.js
Added .catch to the end of the POST fetch request on the registration form. This handles any errors and ensures the page doesn't redirect to if a user cannot be created.
> Add .catch to fetch on Registration

- cypress/integration/Navigation_spec.js
- cypress/integration/Profile_spec.js
- src/components/App.js
- src/components/MenteeRegistration.js
- src/components/MentorRegistration.js
- src/components/Profile.js
- src/components/Register.js
- src/components/SignIn.js
- src/styles/profile-creation.css
Adds: dynamically loaded mentor / mentee sign up components on profile page
Adds : sign in page
Updates: nav to include sign in link
> Profile creation

- cypress/integration/registration_spec.js
- package-lock.json
- package.json
- spec/currentUser_spec.js
- spec/support/jasmine.json
- src/CurrentUser.js
- src/components/App.js
- src/components/NavSignedIn.js
- src/components/NavSignedOut.js
- src/components/Register.js
feat: create CurrentUser constructor, getName retrieves name
feat: can getEmail and setEmail
feat: add getToken and setToken to CurrentUser
feat: sign out (wipes local storage
> Persist user with local storage

- README.md
- cypress/integration/Navigation_spec.js
- cypress/integration/registration_spec.js
- Updated Cypress tests to reflect NavBar changes. 
- Updated README with details of Jasmine testing.
> Refactor Tests due to conditional NavBar and update README

- cypress/integration/registration_spec.js
Removed the expectation that looks out for URL change, so now it checks to see if submit can be clicked.
> Refactor Registration Spec to expect a click on submit. 

- src/components/App.js
- src/components/NavSignedIn.js
- src/components/NavSignedOut.js
- Resolve linting offences. 
- In Registration form, change 'for' to 'htmlFor'.
> Linting fix

- cypress/integration/registration_spec.js
- package-lock.json
- package.json
- src/CurrentUser.js
- src/components/MenteeRegistration.js
- src/components/MentorRegistration.js
- src/components/NavSignedIn.js
- src/components/Register.js
- src/styles/form.css
- Adds the ability for users to create a mentor profile
- Temporarily removes the sign out button
> Create mentor mentee

- spec/currentUser_spec.js
- src/components/Register.js
- When a user registers, the returned auth token is stored in currentUser in localStorage.
> feat: add Auth Token to CurrentUser upon registration

- src/components/NavSignedIn.js
- src/components/SignIn.js
Adds full sign in feature. API is called with email & password, successful response contains user object & auth token, which is then stored in localStorage
> feat: adds sign feature

- cypress/integration/ProfilePage_spec.js
- cypress/integration/registration_spec.js
- src/components/AllMentors.js
- src/components/Mentor.js
- src/components/ProfilePage.js
- src/components/Register.js
- Fetch in AllMentors makes a call using auth token. 
- Update Mentor component with correct data. 
- Update href link in Mentor Component to use user_id rather than mentor ID. This means it takes you to the profile for the User and not the Mentor, that way we can get name and pic. Waiting for API update so we can then receive relevant mentor data and place it in here too.
> /mentors now shows all mentors and links to profile

- cypress/integration/Profile_spec.js
- src/components/Profile.js
Step 1 in personal profile page. The component is now load based on if the user has a mentor / mentee profile.
> Mentor mentee

- src/components/AllMentors.js
- src/components/Mentor.js
> Updates all mentors and mentor component to return info

- src/components/Profile.js
- src/components/Register.js
- src/components/SignIn.js
Adds redirecting after sign in / registration to the profile page
> Personal profile

- src/components/CreateProfile.js
- src/components/MenteeRegistration.js
- src/components/MentorRegistration.js
- src/components/SignIn.js
This fixes errors in the CreateProfile component
> refactor: fixes erros in CreateProfile component

- src/CurrentUser.js
- src/components/MenteeRegistration.js
- src/components/ProfilePage.js
- src/components/Register.js
- Updated CurrentUser to accept a mentee_id when a user creates a mentee profile. 
- Renamed 'Book' button on ProfilePage to 'Request Mentorship' 
- Created a POST request to 'api/mentorships' with the mentee_id of the currentUser and the mentor_id of the currently displayed mentor. 
- Currently, there isn't any visual confirmation of the request being made so I have left a console.log in there for the time being. I'll create another branch to do an actual confirmation.
> Mentorship request

- src/components/SignIn.js
When a user logs in currentUser is updated with Mentee id, bio and interest, and Mentor id, bio and skill. This allows a mentee to request mentorship after they have signed in.
> Login populates current user

- src/components/App.js
- src/components/MentorRegistration.js
- src/components/PersonalProfile.js
Redirects to personal profile page once mentor or mentee form submitted.
> Personal profile page

- cypress/integration/Profile_spec.js
- src/CurrentUser.js
- src/components/AllMentors.js
- src/components/App.js
- src/components/CreateProfile.js
- src/components/MenteeRegistration.js
- src/components/Mentor.js
- src/components/MentorRegistration.js
- src/components/PersonalProfile.js
- src/components/Profile.js
- src/components/ProfilePage.js
- src/components/Register.js
- src/components/SignIn.js
Merges in recent branches:
- adds 'add mentorship' button
- conditional loading of personalProfile
- nav bar changes based on logged in or not
- profile rendered for mentor or mentee
> Profile views, add mentorship 

- src/components/NavSignedOut.js
- src/styles/index.css
- Nudged Sign-in button on navbar down slightly to be in line with rest of navbar.
> fix: align 'sign in' nav button

- package-lock.json
- package.json
- src/components/ProfilePage.js
- src/index.js
- src/styles/confirmation-message.css
A yellow tick animates onto screen once a successful mentorship request has been made, giving visual feedback to the user.
> Request mentorship confirmation

- src/components/ProfilePage.js
- src/styles/form.css
A user can no longer click the request button if they are: 
- Not registered as a mentee
- Trying to request mentorship for themselves
> Only let the user click on request mentorship button in certain circumstances

- src/components/Register.js
feat: new registration now redirects to /profile
> feat: new registration now redirects to /profile

- src/components/CreateProfile.js
- src/components/Register.js
- src/components/SignIn.js
> Personal profile pic

- src/components/ProfilePage.js
Changed the conditional for checking lack of mentee_id on currentUser.
> Fix: Disabling of Mentor Me button

- src/components/MenteeRegistration.js
Labels changed:
- 'bio' -> 'Tell us about yourself:'
- 'interest' -> 'What would you like to be mentored in?'
> Change Mentee registration form labels

- src/components/PersonalProfile.js
Added a check for null and empty string on the conditional.
> Mentee personal profile fix

- src/styles/profilePage.css
- reduce size of profile image and remove margin at top
> Styling on Profile Pic

- src/components/Register.js
Change the tagline on the registration page.
> Copy change on Registration
